services:
  # Database PostgreSQL
  db:
    image: postgres:18-alpine # Versione corrente supportata [15]
    env_file: .env
    shm_size: 128mb
    volumes:
      - pg:/var/lib/postgresql/
      - ./db:/db
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:

volumes:
  pg: {}
