services:

  web:

    build: ./uwsgi/.
    volumes:
      - ./uwsgi:/app

    command: uwsgi --ini uwsgi.ini
    ports:
      - 10001:8001
    stop_signal: SIGINT
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
