[uwsgi]
buffer-size=32768
http = 0.0.0.0:8001
chdir = /app
module = play.wsgi
static-map = /static=/app/STATIC
log-date = true
vacuum = true
max-requests = 5000
auto-procname = true
enable-threads = true
procname-prefix-spaced = iot
touch-reload = %p
harakiri-verbose = true
thunder-lock
stats = 0.0.0.0:1717
stats-http


cheaper-algo = spare
# minimum number of workers to keep at all times
cheaper = 2
# number of workers to spawn at startup
cheaper-initial = 2
# maximum number of workers that can be spawned
workers = 100
# how many workers should be spawned at a time
cheaper-step = 2

socket-timeout = 300
socket-send-timeout = 300
socket-write-timeout = 300
harakiri = 300
http-timeout = 300
